# Generated by Django 5.2.9 on 2026-01-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("department", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("EXPIRED", "Expired"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
