# Generated by Django 5.2.9 on 2026-01-10 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="job",
            old_name="expiry_date",
            new_name="application_end_date",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="description",
            new_name="job_description",
        ),
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.RemoveField(
            model_name="job",
            name="status",
        ),
        migrations.AddField(
            model_name="job",
            name="application_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="apply_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="eligibility",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="exam_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("GOVT", "Government"), ("PRIVATE", "Private")],
                default="GOVT",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="organization",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="selection_process",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="vacancies",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="qualification",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
