# Generated by Django 5.2.9 on 2026-01-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
