# Generated by Django 5.2.9 on 2026-01-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobViewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="job",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active", "application_end_date"],
                name="jobs_job_is_acti_97e514_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "is_active"], name="jobs_job_job_typ_c14aee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["location", "is_active"], name="jobs_job_locatio_073146_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["created_at"], name="jobs_job_created_1b3a4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["views_count"], name="jobs_job_views_c_abb758_idx"
            ),
        ),
        migrations.AddField(
            model_name="jobviewevent",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_events",
                to="jobs.job",
            ),
        ),
        migrations.AddIndex(
            model_name="jobviewevent",
            index=models.Index(
                fields=["job", "created_at"], name="jobs_jobvie_job_id_63dcb6_idx"
            ),
        ),
    ]
