# Generated by Django 5.2.9 on 2026-01-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobviewevent_alter_job_options_job_views_count_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="jobs_job_is_acti_97e514_idx",
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="jobs_job_job_typ_c14aee_idx",
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="jobs_job_locatio_073146_idx",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_active",
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")], default=1
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="jobs_job_status_7d017a_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["application_end_date"], name="jobs_job_applica_82cba1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["job_type"], name="jobs_job_job_typ_f6c220_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location"], name="jobs_job_locatio_8b2f8c_idx"),
        ),
    ]
