# Generated by Django 5.2.9 on 2026-02-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("rank", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "board",
                    models.CharField(
                        choices=[
                            ("AP", "Andhra Pradesh"),
                            ("TS", "Telangana"),
                            ("CBSE", "CBSE"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("rank", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("icon_url", models.URLField(blank=True)),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.academiclevel",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "name"],
                "unique_together": {("level", "slug")},
            },
        ),
        migrations.CreateModel(
            name="AcademicMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document/PDF"),
                            ("IMAGE", "Image/Infographic"),
                            ("LINK", "External Link"),
                            ("EXAM", "Online Exam"),
                            ("CONTENT", "HTML Content"),
                        ],
                        default="CONTENT",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academics.academiccategory",
                    ),
                ),
                (
                    "image_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_images",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academics.academiclevel",
                    ),
                ),
                (
                    "pdf_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_pdfs",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academics.academicsubject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("subject", "slug")},
            },
        ),
    ]
