# Generated by Django 5.2.9 on 2026-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicmaterial",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="academicmaterial",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
