# Generated by Django 5.2.9 on 2026-02-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_academicmaterial_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicmaterial",
            name="content",
        ),
        migrations.RemoveField(
            model_name="academicmaterial",
            name="title",
        ),
        migrations.CreateModel(
            name="AcademicMaterialTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="academics.academicmaterial",
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "language")},
            },
        ),
    ]
