# Generated by Django 5.2.9 on 2026-02-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_remove_academicmaterial_content_and_more"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicmaterial",
            name="image_asset",
        ),
        migrations.RemoveField(
            model_name="academicmaterial",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="academicmaterial",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="academicmaterial",
            name="pdf_asset",
        ),
        migrations.RemoveField(
            model_name="academicsubject",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="academicmaterial",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AcademicMaterialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("BANNER", "Banner Image"),
                            ("INLINE", "Inline Image"),
                            ("DOCUMENT", "Study Material"),
                            ("MODEL_PAPER", "Model Paper/Previous Paper"),
                            ("ATTACHMENT", "General Attachment"),
                        ],
                        default="DOCUMENT",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_links",
                        to="academics.academicmaterial",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="AcademicSubjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage", models.CharField(default="ICON", max_length=50)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media.mediaasset",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_links",
                        to="academics.academicsubject",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
