# Generated by Django 5.2.9 on 2026-02-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_remove_academicmaterial_image_asset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField()),
                ("rank", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="academics.academicsubject",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "id"],
                "unique_together": {("subject", "slug")},
            },
        ),
        migrations.AddField(
            model_name="academicmaterial",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="academics.academicchapter",
            ),
        ),
    ]
