# Generated by Django 5.2.9 on 2026-02-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_academicchapter_academicmaterial_chapter"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicChapterTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="academics.academicchapter",
                    ),
                ),
            ],
            options={
                "unique_together": {("chapter", "language")},
            },
        ),
    ]
