# Generated by Django 5.2.9 on 2026-02-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_academicchaptertranslation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="academicchapter",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="academicmaterial",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="academicsubject",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="academiccategory",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="academiclevel",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="academicchapter",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="academicmaterial",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="academicsubject",
            name="slug",
        ),
    ]
