# Generated by Django 5.2.9 on 2026-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_academicchapter_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicmaterial",
            options={"ordering": ["position", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="academicmaterial",
            name="level",
        ),
        migrations.AddField(
            model_name="academicmaterial",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="AcademicChapterTranslation",
        ),
    ]
