# Generated by Django 5.2.9 on 2026-02-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_alter_academicmaterial_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicmaterialtranslation",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
