# Generated by Django 5.2.9 on 2026-02-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_academicmaterialtranslation_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicmaterial",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="academics.academiccategory",
            ),
        ),
    ]
