# Generated by Django 5.2.9 on 2026-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["entity", "entity_id"], name="common_audi_entity_360a83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="common_audi_action_288430_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user_id"], name="common_audi_user_id_c8d8db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["created_at"], name="common_audi_created_5f768f_idx"
            ),
        ),
    ]
