# Generated by Django 5.2.9 on 2026-01-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articlecategory",
            unique_together={("article", "category")},
        ),
    ]
