# Generated by Django 5.2.9 on 2026-01-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_articlecategory_unique_together"),
        ("taxonomy", "0002_alter_category_options_category_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("TOP", "Top Stories"),
                            ("HERO", "Hero Slider"),
                            ("BREAKING", "Breaking"),
                            ("EDITOR_PICK", "Editor Pick"),
                        ],
                        max_length=20,
                    ),
                ),
                ("section", models.CharField(blank=True, default="", max_length=50)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["rank", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "editor_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="article",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="og_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="article",
            name="og_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="og_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_articles",
                to="taxonomy.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together={("section", "slug")},
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["section", "slug"], name="articles_ar_section_207dba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "section"], name="articles_ar_status_1ff236_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "created_at"], name="articles_ar_status_cbb22b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["expires_at"], name="articles_ar_expires_d220d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlecategory",
            index=models.Index(
                fields=["category", "article"], name="articles_ar_categor_ec8827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articletranslation",
            index=models.Index(
                fields=["language"], name="articles_ar_languag_8cbc05_idx"
            ),
        ),
        migrations.AddField(
            model_name="articlefeature",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="articlerevision",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="articles.article",
            ),
        ),
        migrations.AddIndex(
            model_name="articlefeature",
            index=models.Index(
                fields=["feature_type", "section", "rank"],
                name="articles_ar_feature_c2c97c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="articlefeature",
            index=models.Index(
                fields=["is_active"], name="articles_ar_is_acti_e7b0b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="articlefeature",
            constraint=models.UniqueConstraint(
                fields=("article", "feature_type", "section"),
                name="uniq_article_feature_per_section",
            ),
        ),
        migrations.AddIndex(
            model_name="articlerevision",
            index=models.Index(
                fields=["article", "language", "created_at"],
                name="articles_ar_article_5713ec_idx",
            ),
        ),
    ]
