# Generated by Django 5.2.9 on 2026-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0003_articlefeature_articlerevision_alter_article_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="articlefeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("HERO", "Hero Slider"),
                    ("TOP", "Top Stories"),
                    ("BREAKING", "Breaking"),
                    ("EDITOR_PICK", "Editor Pick"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="articlefeature",
            name="rank",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
