# Generated by Django 5.2.9 on 2026-01-28 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_last_viewed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.CharField(max_length=255)),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("BANNER", "Banner"),
                            ("INLINE", "Inline"),
                            ("GALLERY", "Gallery"),
                            ("ATTACHMENT", "Attachment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_links",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("article", "media_id", "usage")},
            },
        ),
    ]
