# Generated by Django 5.2.9 on 2026-01-28 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_articlemedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlemedia",
            options={"ordering": ["usage", "position"]},
        ),
        migrations.AddField(
            model_name="articlemedia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="articlemedia",
            name="media_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddIndex(
            model_name="articlemedia",
            index=models.Index(
                fields=["article", "usage"], name="articles_ar_article_c01c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlemedia",
            index=models.Index(
                fields=["media_id"], name="articles_ar_media_i_4e66dc_idx"
            ),
        ),
    ]
