# Generated by Django 4.2.15 on 2026-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articlemedia_options_articlemedia_created_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='article_section_slug_idx',
            old_name='articles_ar_section_207dba_idx',
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'noindex'], name='article_status_noindex_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='article_published_at_idx'),
        ),
    ]
