# Generated by Django 4.2.15 on 2026-01-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_articles_ar_section_207dba_idx_article_section_slug_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
    ]
