# Generated by Django 5.2.9 on 2026-02-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_remove_article_summary"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articlemedia",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="articlemedia",
            name="media_id",
        ),
        migrations.RemoveIndex(
            model_name="articlemedia",
            name="articles_ar_media_i_4e66dc_idx",
        ),
        migrations.AddField(
            model_name="articlemedia",
            name="media",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_links",
                to="media.mediaasset",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articlemedia",
            unique_together={("article", "media", "usage")},
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REVIEW", "Review"),
                    ("SCHEDULED", "Scheduled"),
                    ("PUBLISHED", "Published"),
                    ("INACTIVE", "Inactive"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="articlemedia",
            index=models.Index(fields=["media"], name="articles_ar_media_i_4e66dc_idx"),
        ),
    ]
