# Generated by Django 5.2.9 on 2026-03-11 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0009_remove_articlemedia_articles_ar_media_i_4e66dc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlefeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("HERO", "Hero Slider"),
                    ("TOP", "Top Stories"),
                    ("BREAKING", "Breaking"),
                    ("EDITOR_PICK", "Editor Pick"),
                    ("MUST_READ", "Must Read"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="articlemedia",
            name="usage",
            field=models.CharField(
                choices=[
                    ("BANNER", "Banner"),
                    ("MAIN", "Main"),
                    ("INLINE", "Inline"),
                    ("GALLERY", "Gallery"),
                    ("ATTACHMENT", "Attachment"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ArticleSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=50)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_sections",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["section", "article"],
                        name="articles_ar_section_e8d2ae_idx",
                    )
                ],
                "unique_together": {("article", "section")},
            },
        ),
    ]
