# Generated by Django 5.2.9 on 2026-03-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_alter_articlefeature_feature_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="canonical_url",
        ),
        migrations.AddField(
            model_name="article",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
