# Generated by Django 5.2.9 on 2026-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_remove_article_canonical_url_article_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_top_story",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_top_story"], name="articles_ar_is_top__995744_idx"
            ),
        ),
    ]
