# Generated by Django 5.2.9 on 2026-03-11 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_article_is_top_story_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EXAM", "Exam"),
                            ("RESULTS", "Results"),
                            ("ADMISSIONS", "Admissions"),
                            ("SCHOLARSHIPS", "Scholarships"),
                            ("STUDY_TIPS", "Study Tips"),
                            ("JOB_NOTIFICATION", "Job Notification"),
                            ("HOT_TOPIC", "Hot Topic"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("is_top_story", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Top Stories",
                "ordering": ["-publish_date", "-id"],
            },
        ),
    ]
