# Generated by Django 5.2.9 on 2026-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_topstory"),
    ]

    operations = [
        migrations.AddField(
            model_name="topstory",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
