# Generated by Django 5.2.9 on 2026-03-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0014_topstory_title"),
        ("media", "0001_initial"),
        ("taxonomy", "0003_section_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topstory",
            options={
                "ordering": ["rank", "-publish_date", "-id"],
                "verbose_name_plural": "Top Stories",
            },
        ),
        migrations.RemoveField(
            model_name="topstory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="topstory",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="topstory",
            name="title",
        ),
        migrations.AddField(
            model_name="topstory",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="topstory",
            name="description_te",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="topstory",
            name="rank",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topstory",
            name="title_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="topstory",
            name="title_te",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="topstory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top_stories",
                to="taxonomy.category",
            ),
        ),
        migrations.CreateModel(
            name="TopStoryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_story_links",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "top_story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_links",
                        to="articles.topstory",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "unique_together": {("top_story", "media")},
            },
        ),
    ]
