# Generated by Django 5.2.9 on 2026-02-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_key", models.CharField(max_length=500, unique=True)),
                ("file_size", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("doc", "Document"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("academics", "Academics"),
                            ("jobs", "Jobs"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=100)),
                ("language", models.CharField(default="en", max_length=5)),
                ("uploaded_by_user_id", models.CharField(max_length=100)),
                ("uploaded_by_role", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["purpose", "section"],
                        name="media_media_purpose_8bbe27_idx",
                    ),
                    models.Index(
                        fields=["media_type"], name="media_media_media_t_2921f5_idx"
                    ),
                    models.Index(
                        fields=["is_active", "is_deleted"],
                        name="media_media_is_acti_438b88_idx",
                    ),
                ],
            },
        ),
    ]
