# Generated by Django 5.2.9 on 2026-03-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("taxonomy", "0002_alter_category_options_category_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rank", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="taxonomy_ca_section_bfce33_idx",
            old_name="taxonomy_ca_section_a652c3_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="taxonomy_ca_section_381634_idx",
            old_name="taxonomy_ca_section_0c4fbd_idx",
        ),
        migrations.AddField(
            model_name="category",
            name="content",
            field=models.TextField(blank=True, help_text="Rich text / HTML content"),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_images",
                to="media.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="language",
            field=models.CharField(default="te", max_length=5),
        ),
        migrations.AddField(
            model_name="category",
            name="pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_pdfs",
                to="media.mediaasset",
            ),
        ),
        migrations.RemoveField(
            model_name="category",
            name="section",
        ),
        migrations.AddField(
            model_name="category",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="taxonomy.section",
            ),
        ),
    ]
